// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/vo/Address.vue')['default']
    Ai: typeof import('./src/components/Ai.vue')['default']
    AiGrid: typeof import('./src/components/ui/AiGrid.vue')['default']
    Author: typeof import('./src/components/Author.vue')['default']
    AuthorGrid: typeof import('./src/components/ui/AuthorGrid.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    BookGrid: typeof import('./src/components/ui/BookGrid.vue')['default']
    BookService: typeof import('./src/components/BookService.vue')['default']
    BookServiceGrid: typeof import('./src/components/ui/BookServiceGrid.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    Email: typeof import('./src/components/vo/Email.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    File: typeof import('./src/components/vo/File.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    Money: typeof import('./src/components/vo/Money.vue')['default']
    MypageView: typeof import('./src/components/MypageView.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    Payment: typeof import('./src/components/vo/Payment.vue')['default']
    Photo: typeof import('./src/components/vo/Photo.vue')['default']
    Rating: typeof import('./src/components/vo/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    String: typeof import('./src/components/primitives/String.vue')['default']
    Subscribe: typeof import('./src/components/Subscribe.vue')['default']
    SubscribeGrid: typeof import('./src/components/ui/SubscribeGrid.vue')['default']
    Subscriber: typeof import('./src/components/Subscriber.vue')['default']
    SubscriberGrid: typeof import('./src/components/ui/SubscriberGrid.vue')['default']
    SubscribeViewView: typeof import('./src/components/SubscribeViewView.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    User: typeof import('./src/components/vo/User.vue')['default']
    Weather: typeof import('./src/components/vo/Weather.vue')['default']
    Writing: typeof import('./src/components/Writing.vue')['default']
    WritingGrid: typeof import('./src/components/ui/WritingGrid.vue')['default']
    '포인트': typeof import('./src/components/포인트.vue')['default']
    '포인트Grid': typeof import('./src/components/ui/포인트Grid.vue')['default']
  }
}
