name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./author/pom.xml
          mvn clean package -f ./subscription/pom.xml
          mvn clean package -f ./writing/pom.xml
          mvn clean package -f ./point/pom.xml
          mvn clean package -f ./review/pom.xml
          mvn clean package -f ./ai/pom.xml
          mvn clean package -f ./book/pom.xml
          mvn clean package -f ./dashboard/pom.xml

      - name: Docker Build and push for Author
        uses: docker/build-push-action@v4
        with:
          context: ./author
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/author:latest
            ghcr.io/${{ github.repository }}/author:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscription
        uses: docker/build-push-action@v4
        with:
          context: ./subscription
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscription:latest
            ghcr.io/${{ github.repository }}/subscription:${{ github.ref_name }}
            
      - name: Docker Build and push for Writing
        uses: docker/build-push-action@v4
        with:
          context: ./writing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/writing:latest
            ghcr.io/${{ github.repository }}/writing:${{ github.ref_name }}
            
      - name: Docker Build and push for Point
        uses: docker/build-push-action@v4
        with:
          context: ./point
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point:latest
            ghcr.io/${{ github.repository }}/point:${{ github.ref_name }}
            
      - name: Docker Build and push for Review
        uses: docker/build-push-action@v4
        with:
          context: ./review
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/review:latest
            ghcr.io/${{ github.repository }}/review:${{ github.ref_name }}
            
      - name: Docker Build and push for Ai
        uses: docker/build-push-action@v4
        with:
          context: ./ai
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai:latest
            ghcr.io/${{ github.repository }}/ai:${{ github.ref_name }}
            
      - name: Docker Build and push for Book
        uses: docker/build-push-action@v4
        with:
          context: ./book
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/book:latest
            ghcr.io/${{ github.repository }}/book:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
